#!/usr/bin/env node
/* ============================================================================
   Fetch and self-host the interface typefaces.

   Runs in Actions because the sandbox cannot reach Google's font servers.
   Self-hosting rather than linking has three advantages: the pages carry no
   third-party dependency, they do not leak visitors to another host, and the
   authoring session can actually SEE the typography it is shipping.

   Both families are licensed under the SIL Open Font License, which permits
   redistribution. The licence is written alongside the files.

     node scripts/fetch-fonts.mjs
   ========================================================================= */

import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(ROOT, 'site', 'assets', 'fonts');

/* A modern browser UA, so Google serves woff2 with unicode-range subsets. */
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FAMILIES = [
  { name: 'Inter',         css: 'Inter:wght@400;500;600;700',        file: 'inter' },
  { name: 'Space Grotesk', css: 'Space+Grotesk:wght@500;600;700',    file: 'space-grotesk' },
];

async function get(url, asText = true) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} for ${url}`);
  return asText ? res.text() : Buffer.from(await res.arrayBuffer());
}

async function main() {
  await mkdir(DIR, { recursive: true });
  const blocks = [];

  for (const fam of FAMILIES) {
    console.log(`\n=== ${fam.name}`);
    const css = await get(`https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`);

    // Keep only the latin subsets; the rest is weight the site never uses.
    const faces = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g)]
      .filter(m => /^latin(-ext)?$/.test(m[1]));

    let i = 0;
    for (const [, subset, body] of faces) {
      const url = body.match(/url\(([^)]+)\)\s*format\('woff2'\)/)?.[1];
      const weight = body.match(/font-weight:\s*(\d+)/)?.[1] || '400';
      const range = body.match(/unicode-range:\s*([^;]+);/)?.[1];
      if (!url) continue;

      const file = `${fam.file}-${weight}-${subset}.woff2`;
      const buf = await get(url, false);
      await writeFile(join(DIR, file), buf);
      console.log(`  ${file}  ${(buf.length / 1024).toFixed(0)} KB`);

      blocks.push(`@font-face {
  font-family: '${fam.name}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('fonts/${file}') format('woff2');${range ? `\n  unicode-range: ${range};` : ''}
}`);
      i++;
    }
    if (!i) console.log('  NOTHING MATCHED — check the CSS response');
  }

  const header = `/* ============================================================================
   Self-hosted interface typefaces.

   Generated by scripts/fetch-fonts.mjs — do not edit by hand.

   Inter and Space Grotesk are both licensed under the SIL Open Font License
   1.1, which permits redistribution with the font files. See fonts/OFL.txt.
   ========================================================================= */

`;
  await writeFile(join(ROOT, 'site', 'assets', 'fonts.css'), header + blocks.join('\n\n') + '\n');
  await writeFile(join(DIR, 'OFL.txt'),
    'Inter — Copyright (c) The Inter Project Authors.\n' +
    'Space Grotesk — Copyright (c) The Space Grotesk Project Authors.\n\n' +
    'Both families are licensed under the SIL Open Font License, Version 1.1.\n' +
    'https://scripts.sil.org/OFL\n');
  console.log(`\n${blocks.length} font face(s) written to assets/fonts.css`);
}

main().catch(e => { console.error(e); process.exit(1); });
